//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam_ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Akcii
    {
        public int Idakcii { get; set; }
        public string Description { get; set; }
        public int Discount { get; set; }
        public System.DateTime start { get; set; }
        public System.DateTime stop { get; set; }
    }
}
