//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam_ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public int Idbook { get; set; }
        public string Title { get; set; }
        public int Cost { get; set; }
        public int Year { get; set; }
    }
}
