//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam_ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Books()
        {
            this.Sales = new HashSet<Sales>();
            this.parts = new HashSet<Books>();
            this.is_parts = new HashSet<Books>();
        }
    
        public int Idbook { get; set; }
        public string Title { get; set; }
        public int Cost { get; set; }
        public int Year { get; set; }
        public int Count { get; set; }
        public Nullable<int> Cost_self { get; set; }
        public Nullable<int> Pages { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Genre Genre { get; set; }
        public virtual Authors Authors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sales> Sales { get; set; }
        public virtual Akcii Akcii { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Books> parts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Books> is_parts { get; set; }
        public virtual Publisher Publisher { get; set; }
    }
}
